## Styling The SPA
sneeu-leeu/bookstore pull request #4
Opened 2021-08-31 14:26 UTC by sneeu-leeu

## In this Milestone I:
- Used Bootstrap
- Use the information detailed in Zeplin to style the website.
- Your final design should match Zeplin's design.

2021-08-31 14:44 UTC, sneeu-leeu commented
## PLEASE NOTE 
## DUE TO THE NATURE AND SPECIFICITY OF  THE MEASUREMENTS WE HAD TO FOLLOW FOR THIS PROJECT, THE AUTHOR OF THIS PROJECT USED 75% ZOOM IN BROWSER TO BUILD. PLEASE FIND THE RIGHT ZOOM FOR YOUR MONITOR BEFORE REVIEW

2021-08-31 17:06 UTC, vichuge commented
> ## PLEASE NOTE
> ## DUE TO THE NATURE AND SPECIFICITY OF THE MEASUREMENTS WE HAD TO FOLLOW FOR THIS PROJECT, THE AUTHOR OF THIS PROJECT USED 75% ZOOM IN BROWSER TO BUILD. PLEASE FIND THE RIGHT ZOOM FOR YOUR MONITOR BEFORE REVIEW

- I understand the request but talking about a professional environment, please imagine a company publishing an official announcement saying "Please, consider using 75% zoom when entering on my page, in that way you'll be able to use our page, thanks". I think is not an appropriate request for all the users on that page don't you think? 🧛

2021-08-31 17:06 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- One important thing on this project is make the design EXACTLY the same as the template.

| zeplin project | your project |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/131543142-5cc1605a-fdda-487c-86c6-694137fb74b3.png) | ![image](https://user-images.githubusercontent.com/20563252/131543963-38f33c91-2c1d-4b09-aa55-35943717d7b9.png) |

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +.App {
- [x] It looks like you have a big space on the top page without any reason, please, remove this unnecessary point. 🐶

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +.header-text {
- [x] Please add boldness to the title, this will help the app to be more according to the template. 🐰

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +.book-title {
- [ ] The font for the book title could change to be more according to the template, please work on it. 🦊

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +.book-panel {
- [ ] It looks like there is a margin/padding problem with the book panel, this is outside the square, please, fix it. 🍓 
![image](https://user-images.githubusercontent.com/20563252/131544528-aa102122-1818-4d33-8e66-a4046ed0c224.png)

2021-08-31 17:06 UTC, vichuge commented on src/App.js
> +          <header className="header bg-white p-3 d-flex align-items-center mb-4">
- [ ] It looks like the header could improve the color a little bit, I know the bg said white but, comparing it to the book element, it could have the same white as the element, don't you think? 🐱 
![image](https://user-images.githubusercontent.com/20563252/131545071-e1abc79a-ceaa-4ed2-aadb-fb38f46de6be.png)

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +.add-new-book {
- [ ] Add new book title looks thin,  why not add boldness to this. 🌴

2021-08-31 17:06 UTC, vichuge commented on src/components/books.jsx
> +        <button type="button" className="btn add-book-button" onClick={submitToBookStore}>ADD BOOK</button>
- [ ] Add Book button looks outside the square, please fix this. 🥥 
![image](https://user-images.githubusercontent.com/20563252/131545330-568ce2d4-0f66-4623-a3a7-15de6da9c6d0.png)

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +  text-decoration: none !important;
- [ ] Please, don't use ! important tag, this is a bad practice and change the CSS flow on the project. 🌮

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +  padding: 0.3rem 0.7rem 0.5rem 1rem !important;
- [ ] Please, don't use ! important tag, this is a bad practice and change the CSS flow on the project. 🌮

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +  background-color: #0290ff !important;
- [ ] Please, don't use ! important tag, this is a bad practice and change the CSS flow on the project. 🌮

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +  color: #fff !important;
- [ ] Please, don't use ! important tag, this is a bad practice and change the CSS flow on the project. 🌮

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +  background-color: #0290ff !important;
- [ ] Please, don't use ! important tag, this is a bad practice and change the CSS flow on the project. 🌮

2021-08-31 17:06 UTC, vichuge commented on src/App.css
> +  color: #fff !important;
- [ ] Please, don't use ! important tag, this is a bad practice and change the CSS flow on the project. 🌮

2021-09-03 10:44 UTC, Temmarie commented
Hello  @sneeu-leeu  :wave:
_This is an additional review as a result of the second opinion request._

You complained about the code reviewer asking you to change the design to match the one in Zeplin and to not overuse `!important` in your CSS file.

Note that each review made by the code reviewer is guided by the provided project guidelines.

About `!important`, the code reviewer meant that you should not overuse them, not that they should not be used at all. In your case, you have overused the tags and have to make the necessary changes to remove them and only use them when compulsory. Kindly refer to the [HTML/CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md). 

Also, the project requirements say to style your project to be EXACTLY the same as the one in Zeplin. So using a screen size of 75% clearly goes against that requirement.  
![image](https://user-images.githubusercontent.com/49621279/131993109-65dceb8e-63d9-46a2-913e-ba05c480a20e.png)

I can see that you have implemented some of the required changes, so kindly implement the remaining ones and submit them for review. 
I hope this helps to resolve the issue.

Happy coding!

2021-09-03 10:57 UTC, sneeu-leeu commented
@Temmarie, could you please advise further: 
- My project as shown in the screengrabs provided when asking for a second opinion use the exact rem measurements as specified in the Zeppelin Project, that is why I have to zoom the page. Because the specifications are too big for a normal screen?
- How many times are 'too much' for the !important tag, as I only used it on 2 elements that are overrided by Bootstrap.

2021-09-03 11:52 UTC, Temmarie commented
Hi @sneeu-leeu,

After our private talk and upon further investigation, you don't have to change the use of !important, since you used them to over ride some Bootstrap styles. So your project will be approved after you fix the issues with the width. I hope we've been able to resolve the issue.

**_To the next code reviewer, kindly approve this project!_**

Happy coding!!

2021-09-03 12:23 UTC, ZawadiSumba66 approved these changes
Hi @sneeu-leeu 👋 ,
## STATUS: APPROVED 👍 
Great job implementing the changes requested by the previous reviewer!! 👏  
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-03 20:42 UTC, merged